### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by znpfg** [mpmc/HS602#11]
Hi, I'm author of review for Supercast T3  you linked in top page.

I'm very beginner like this development stuff, so I need your help.
When I extracted file in user space, I got error message.
So I extracted into library folder in program files directory, but got
another error message. 
The driver already installed using skydigital one.
OS: windows 10 x64 

Here's my result.
Any requirement I missed setup?

```
C:\Program Files\Python39\Lib\hs602>example.py
This is an example script to control the HS602 capture device..
Press enter to continue, or ctrl+c to exit.
Please wait..
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Program Files\Python39\Lib\hs602\example.py", line 37, in main
    device = Controller(devices[0])
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Python39\Lib\hs602\example.py", line 147, in <module>
    sys.exit(main(sys.argv))
  File "C:\Program Files\Python39\Lib\hs602\example.py", line 39, in main
    raise Exception('No devices, maybe crashed?') from exc
Exception: No devices, maybe crashed?
```

I'm very appreciate of your project to extend and improve for this device.

**Comment by mpmc** [comment]
Sorry for the very late reply. Seems the script can't find your device, or it never got a reply from it. You don't actually need the driver installed at all (having it installed doesn't matter as long as the app isn't running). Also bare in mind that this script will only work with the device connected to your network not via usb on your computer. Firewalls can block the script too.

**Comment by znpfg** [comment]
I was wrong. I thought the mode should be set as PC-mode, not as standalone streaming mode.
It works fine with streaming mode. Appreciate your help!
